services:
  db:
    image: mysql:8.0.35
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - net01
      
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - net01

volumes:
  data:

networks:
  net01: